package sew.ai.enums;

public enum ConfigProperties {
    URL,
    USERNAME,
    PASSWORD,
    OVERRIDE_REPORTS,
    PASSED_STEPS_SCREENSHOT,
    FAILED_STEPS_SCREENSHOT,
    SKIPPED_STEPS_SCREENSHOT,
    RETRY_FAILED_TESTS,
    RUN_MODE,
    SEND_RESULT_TO_ELK,
    SELENIUM_GRID_URL,
    ELASTIC_URL
}
